name: Java CI

on: [push]

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn compile hpi:hpi

      - name: create release
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/jenkins-oss.hpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}